pipeline:
  build:
    image: node:8
    volumes:
      - /usr/local/share/drone:/var/hostdata/
    commands:
      - cat /etc/issue
      - ls -l /var/hostdata/yanzhipeng.ovpn
      - ls -l /var/hostdata/sources.list
      - apt-get update
      - npm install
      - npm run build
