pipeline:
  build:
    image: node:8
    volumes:
      - /usr/local/share/drone:/var/hostdata/
    commands:
      - cat /etc/issue
      - ls -l /var/hostdata/yanzhipeng.ovpn
      - ls -l /var/hostdata/sources.list
      - mv /etc/apt/sources.list /etc/apt/sources.list.bak
      - cp /var/hostdata/sources.list /etc/apt
      - apt-get update
      - apt-get install -y openvpn
      - man openvpn
      - npm install
      - npm run build
