pipeline:
  build:
    image: node:8
    volumes:
      - /etc/openvpn/yanzhipeng.ovpn:/etc/openvpn/yanzhipeng.ovpn
    commands:
      - lsb_release -a
      - apt install openvpn
      - openvpn --daemon --cd /etc/openvpn --config yanzhipeng.ovpn --log-append /var/log/openvpn.log
      - npm install
      - npm run build
