pipeline:
  build:
    image: node:8
    volumes:
      - /var/vpn/yanzhipeng.ovpn:~/yanzhipeng.ovpn
    commands:
      - lsb_release -a
      - apt install openvpn
      - npm install
      - npm run build
