pipeline:
  build:
    image: node:8
    volumes:
      - /etc/openvpn:/var/vpn/
    commands:
      #- apt install --assume-yes openvpn
      - openvpn /var/vpn/yanzhipeng.ovpn
      - npm install
      - npm run build
