pipeline:
  build:
    image: node:8
    volumes:
      - /etc/openvpn:/var/vpn/
    commands:
      - cat /etc/issue
      - apt-get update
      - apt-get install -y openvpn
      - openvpn --daemon /var/vpn/yanzhipeng.ovpn
      - npm install
      - npm run build
