pipeline:
  build:
    image: node:8
    cap_add:
      - net_admin
    volumes:
      - /usr/local/share/drone:/var/hostdata/
      - /dev/net:/dev/net:z
    commands:
      - cat /etc/issue
      - ls -l /var/hostdata/yanzhipeng.ovpn
      - ls -l /var/hostdata/sources.list
      - mv /etc/apt/sources.list /etc/apt/sources.list.bak
      - cp /var/hostdata/sources.list /etc/apt
      - apt-get update
      - apt-get install -y openvpn
      - which openvpn
      - ls /var/hostdata
      - openvpn /var/hostdata/yanzhipeng.ovpn &&
      - npm install
